### PR TITLE
Some helper scripts for win32

### PR DESCRIPTION
**Pull request by aismann**

### CODE REVIEW

**Comment by halx99** [comment]
the ci failed

**Comment by halx99** [comment]
well, you change the README.md, I have plan to tidy readme

* README.md: for english only
* README_CN.md: for china only

**Comment by aismann** [comment]
> Do you have any recommand about engine-x readme and interest to finish english readme.md?
 Im not a nativ english speaker/writer. Also Im not really inform how you can build other platform as Windows/VS2019.
I belive Im the wrong person for your choose. Sorry.

**Comment by halx99** [comment]
ok, but the download-deps.py is required by CI/CD, so I think you shouldn't rename it.

**Comment by aismann** [comment]
The easiest way is tho reject this pull request.
I have no problem with this.

**Comment by aismann** [comment]
closed

**Comment by halx99** [comment]
Yeah, use readme to guide build step is better

**Comment by halx99** [comment]
different project will have it's own CI/CD build script

**Pull request closed without merging**
