### PR TITLE
Add utils::createInstance to instead macro CREATE_FUNC

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by aismann** [comment]
What is the reason?
Any API changes too?

**Comment by halx99** [comment]
No chnages, just add the new API

**Comment by halx99** [comment]
Simple usage:
```cpp
struct LevelData {
 // ...
};
class LevelScene : public Scene
{
public:
    bool initWithLevelData(const LevelData& data) {
        if(!Scene::init()) return false;
        // don somethings init with the levelData
    }
};

// Then the scene can be create anywhere with the custom init function 'initWithLevelData'
auto scene = utils::createInstance<LevelScene>(&LevelScene::initWithLevelData, levelData);
```

**Comment by aismann** [comment]
Ist there any cpptest example?
Documentation about new API too?

**Comment by halx99** [comment]
The ```cpp-empty-tests``` and the template project ```HelloCpp``` use the new API

**Pull request merged**
